server:
  port: 8200
  error.include-stacktrace: never

spring:
  application.name: movie-info-service

management.endpoints.web.exposure.include: "*"

tmdb:
  base_url: https://api.themoviedb.org/3/
  api_key: 525074f1f0ee4cd494ffe0adee6b0074
