server:
  port: ${PORT:8200}
  error.include-stacktrace: never

management.endpoints.web.exposure.include: "*"

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${spring.application.name}
    # registers with ip address instead of hostname
    preferIpAddress: false
